### PR TITLE
Fix/source info relative

### PR DESCRIPTION
**Pull request by ryuran**
- Fix relative source
- add a base path directory to be reference of relative path
- updates dependencies

### CODE REVIEW

**Comment by ryuran** [comment]
Maybe some doc should be add in readme for new base option.

**Comment by RobLoach** [comment]
Looks like a good thing to have. Thanks for adding this. Outside of documentation, is there anything else you think we should add?

**Comment by sntran** [comment]
This looks good. The output is a little different than expected though, but I'm not sure it's important.

Before, the path is relative to the `source` option. Now, it includes the `source` path.

For example, after running `kss --source='css' --mask='*.less|*.sass|*.scss'`, the generated style guide references to `css/app.css`. Before, it used to be just `app.css`.

Again, it does not make a difference to me, but it's up to y'all.

**Comment by ryuran** [comment]
@sntran Yes for sure.

`kss --source="['css', 'otherplace/css']"`

In this way, we can’t know what should be the referential directory to resolve relative path 😢 

@RobLoach nothing to add, maybe some text but I have a question about API :

## Before
- source = directory path
- mask = filter files

## After
- base = reference directory
- source = path with wildcards to find source
- mask = filter files

Use glob pattern in `source` make `mask` option useless.
`source` could be useless if we only need a directory (replaced by `base`)

## But why not
- source = reference directory (current base / old source)
- includes = path with wildcards to find source (current source)
- mask = filter files

This way will not break the old API.

**Comment by ryuran** [comment]
@sntran @RobLoach 
What do you prefer ?

# ❤️ 
- base = reference directory
- source = paths with wildcards to find source
- mask = filter files

# 🎉 
- source = reference directory (current base / old source)
- includes = paths with wildcards to find source (current source)
- mask = filter files

# 👀 
- source = reference directory (current base / old source)
- mask = wildcards to find source (mix current source & mask)

**Comment by sntran** [comment]
I was not aware that you can pass an array of `source`. In that case, what you have is perfect! :shipit:

**Comment by ryuran** [comment]
Its up to date @RobLoach @sntran
Review open.

**Comment by curtisj44** [comment]
Hi. Are there plans to put this out on NPM in the next beta release (`.26`)?

**Pull request merged**
