### PR TITLE
Prefer global install

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by ryuran** [comment]
I'm not agree.

I do not recommand to install modules globaly.
It should always be versioned in package.json in the project.

For KSS we don't use same version in multiple project (old project vs new project, manage version globaly is inferno. And how to share the version number with other developers ?

**Comment by DanielRuf** [comment]
Well, kss-node is written as binary and the docs also say `Usage: kss [options]`.

It does not force a global installation and just gives a warning that a global installation is preferred.

**Comment by DanielRuf** [comment]
https://github.com/kss-node/kss-node/wiki/Quick-Start-Guide is different to the readme and the readme is used / shown on npmjs.

**Comment by ryuran** [comment]
@DanielRuf By experience install globaly is never a good choice in time.
Project code and global instalation are never synchronized.

If a project use new kss v5 and an other one use old v3 It can't work with one package intalled globaly.
Switch version / project is a pain with global intalation

I remember `gulp` and `grunt` was `preferGlobal: true`
Gulp choose to remove it in favor of `gulp-cli`.
https://github.com/gulpjs/gulp/commit/2745033aafa72b573d30e0b5d46d6d3aebc7f46a#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

But KSS is not only a CLI, and CLI it's not separated from parser and builder.
And KSS CLI is strongly related to builder.

Furthermore KSS is part of some starter-kit.

So i disagree to set preferGlobal to true if it's not always "prefered".
I know what I do. I don't want to see a warning message saying it's not the better way, mostly if I know it's false in my case.
And I don't want to have to explain to my junior dev "ignore this warning, it's not relevant in our case".

**Pull request closed without merging**
