### PR TITLE
Update dependencies and add newer Node.js versions

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Comment by adidahiya** [comment]
Bump on this @RobLoach, anything we can do to help it along?

**Comment by RobLoach** [comment]
Thanks!

**Comment by Jassiuf** [comment]
Hi, I am migrating a project from 3.0.0-beta25 to 3.0.1. Builds started failing when I did that.

 I saw you Node 8 was removed from this .travis.yml. Do I need to upgrade the project nodejs version to 10 onwards in order to  use your library?

**Comment by RobLoach** [comment]
Node 8 went out of maintenance in January, 2020. While we don't support Node.js 8, it doesn't mean it won't work. I'd recommend upgrading to the current or active release of Node.js:
https://nodejs.org/en/about/releases/

Anything above Node.js 12 would be good.

What failures were you getting in 3.0.1?

**Pull request merged**
