### PR TITLE
Feature/colors

### PR DESCRIPTION
**Pull request by ryuran**
rainbow

capture d ecran 2018-05-24 a 14 15 42

- [x] add test to section lib
- [x] test support of css custom property `--var`
- [x] add support of color keywords https://www.w3.org/wiki/CSS/Properties/color/keywords

### CODE REVIEW

**Comment by ryuran** [comment]
Some test are missing

**Comment by RobLoach** [comment]
This is looking great! :+1:

**Comment by ryuran** [comment]
I should add doc for this feature in https://github.com/kss-node/kss.
I think everything is OK, I wait for your review @RobLoach.

**Comment by RobLoach** [comment]
Looks great! Nicely done. Mind adding some documentation around it?

**Pull request merged**
