### PR TITLE
WIP: Update README.md

### PR DESCRIPTION
**Pull request by rcaracaus**

### CODE REVIEW

**Comment by JohnAlbin** [comment]
WIP?

**Comment by attiks** [comment]
wip = Work In Progress

**Comment by JohnAlbin** [comment]
Yes, I know. :-)

I was intending to ask why it was still "work in progress".

**Comment by attiks** [comment]
My bad

**Comment by JohnAlbin** [comment]
I've changed the Installation instructions in the README to point at the new wiki Quick Start guides that I wrote on the plane ride over to Drupalcon. https://github.com/kss-node/kss-node/wiki

**Pull request closed without merging**
