### PR TITLE
Add responsive focus link for each section

### PR DESCRIPTION
**Pull request by jnowland**
Makes it easy to test a component's screen size responsiveness in the current style guide.
Allows the element to be launched outside of the container via the `:fullscreen` api.  #165.

This new functionality required  new javascript file for dependancy to bring in this feature.

### CODE REVIEW

**Comment by JohnAlbin** [comment]
This works really well. Unfortunately, I don't find it that useful.

The idea behind "responsive focus" is that an element becomes full-<em>viewport</em> (not full-screen), so you can still resize the window to see how it changes at different viewport sizes.

**Comment by JohnAlbin** [comment]
Oh, hmm… I didn't realize you could open the browser's DOM inspector in full screen mode.

Hmm… this is still better than what we have now, which is nothing. I'll work on merging this with the 3.x branch.

**Comment by JohnAlbin** [comment]
I can't get the CSS to apply in any browser. :-\

**Comment by jnowland** [comment]
@JohnAlbin is this the `:fullscreen` css classes?  If the elements are in fullscreen mode that `:fullscreen` should be available on all elements.

**Comment by JohnAlbin** [comment]
Yep. I click on the link you added, the element goes into full screen and the CSS doesn't apply. In any browser. :-\

**Comment by RobLoach** [comment]
https://github.com/kss-node/kss-node/pull/313 may be related. Looks like this PR could either be rebased and updated, or focus could move to the other PR. Pun completely intended.

**Comment by JohnAlbin** [comment]
I went with a simpler "full window" focus method. https://github.com/kss-node/kss-node/issues/165#issuecomment-258776293

**Pull request closed without merging**
